name: Publish Nuget Package

on:
  push:
    branches:
      - main

env:
  PROJECT: src/Xin.Ordinatus/Xin.Ordinatus.csproj


jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT }}

      - name: Build solution
        run: dotnet build ${{ env.PROJECT }} --configuration Release --no-restore

      - name: Pack solution
        run: dotnet pack ${{ env.PROJECT }} --configuration Release --no-build -o ./output

      - name: Publish package to NuGet
        run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
